name: admin-ui-switchboard
namespace: official
version: 1.0.0
author: Wazo Team
display_name: Switchboard
min_wazo_version: 17.16
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-switchboard
