name: admin-ui-switchboard
namespace: official
version: 1.1.0-2
author: Wazo Team
display_name: Switchboard
min_wazo_version: 18.01
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-switchboard
