name: admin-ui-switchboard
namespace: official
version: 0.0.1
author: Wazo Team
display_name: Switchboard
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-switchboard
